name: "action-testmo-ext"
description: "Upload test results to testmo with custom uploader"
author: "Epsy Engineering <engieering@epsyhealth.com>"

inputs:
  action:
    description: Name of the action to be executed
    required: true
    default: upload

  testmo_user:
    description: Testmo user to use for automation
    required: true

  testmo_password:
    description: Password
    required: true

  testmo_endpoint:
    description: Testmo endpoint
    required: true

  project_id:
    description: Testmo Project ID
    required: true

  service:
    description: Name of the service tested
    required: true

  feature:
    description: Name of the feature
    required: false

  feature_link:
    description: Link to the feature
    required: false

  features:
    description: Link to the feature
    required: false

  pr:
    description: Link to the PR which was tested

  ci_run:
    description: Url to CI run

  version:
    description: Tested version

  report:
      description: Report file to be uploaded

outputs:
  run_url:
    description: URL


runs:
  using: "docker"
  image: "docker://epsyhealth/action-testmo-ext"
